/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor_simuladorbancario;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author rafael
 */
public class GUI2 extends javax.swing.JFrame {

    private MyServerSocket mySocket;
    private Thread t;
    private Socket connectionServ;
    private Socket connectionServLog;
    private Socket connectionServArq;
    private Socket connectionServBorda;
    private Thread tServLog;
    private DataInputStream dis = null;
    private DataOutputStream dos = null;
    private Thread tServ;
    private Thread tServArq;
    private Thread tServBorda;
    private String resultIp = null;

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
        
    }

    public static InetAddress getCurrentIp() {
        try {
            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface
                    .getNetworkInterfaces();
            while (networkInterfaces.hasMoreElements()) {
                NetworkInterface ni = (NetworkInterface) networkInterfaces
                        .nextElement();
                Enumeration<InetAddress> nias = ni.getInetAddresses();
                while (nias.hasMoreElements()) {
                    InetAddress ia = (InetAddress) nias.nextElement();
                    if (!ia.isLinkLocalAddress()
                            && !ia.isLoopbackAddress()
                            && ia instanceof Inet4Address) {
                        return ia;
                    }
                }
            }
        } catch (SocketException e) {
            //LOG.error("unable to get current IP " + e.getMessage(), e);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btInicia = new javax.swing.JButton();
        btPara = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbIp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfSaldo = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        btCadastra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVIDOR");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Status do Servidor:");

        lbStatus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 0, 0));
        lbStatus.setText("OFFLINE");

        btInicia.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btInicia.setText("Iniciar Servidor");
        btInicia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciaMouseClicked(evt);
            }
        });

        btPara.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btPara.setText("Parar Servidor");
        btPara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btParaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("OPÇÕES:");

        lbIp.setText("0.0.0.0");

        jLabel2.setText("Servidor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbStatus)
                .addGap(34, 34, 34)
                .addComponent(lbIp)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btInicia)
                                .addGap(18, 18, 18)
                                .addComponent(btPara))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addGap(100, 100, 100)))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(285, 285, 285))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(82, 82, 82)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInicia)
                    .addComponent(btPara))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbStatus)
                    .addComponent(lbIp))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Servidor", jPanel1);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Senha:");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Saldo:");

        tfNome.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        tfSaldo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoActionPerformed(evt);
            }
        });

        tfSenha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        btCadastra.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btCadastra.setText("CADASTRAR");
        btCadastra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(tfSaldo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(btCadastra)
                .addGap(249, 249, 249))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btCadastra)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro de Clientes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaldoActionPerformed

    private void btIniciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciaMouseClicked
        mySocket = new MyServerSocket();
        t = new Thread(mySocket);
        t.start();
        lbStatus.setText("ONLINE");
        lbStatus.setForeground(Color.green);

        resultIp = GUI2.getCurrentIp().toString().replace("/", "");

        lbIp.setText(resultIp);
        
        recebeClientes();

        try {
            connectionServLog = new Socket(SharedResources.getInstance().getServers().get(1), 8090);
            TrataConexaoServidorLog trataServidoresLog;
            trataServidoresLog = new TrataConexaoServidorLog(connectionServLog, "Servidor " + resultIp + " online!\n");
            tServLog = new Thread(trataServidoresLog);
            tServLog.start();
        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(0));
        } catch (IndexOutOfBoundsException ex) {

        }
        
        try {
            connectionServBorda = new Socket(SharedResources.getInstance().getServers().get(0), 9010);
            TrataConexaoServidorBorda trataServidorBorda;
            trataServidorBorda = new TrataConexaoServidorBorda(connectionServBorda,resultIp,"o");
            tServBorda = new Thread(trataServidorBorda);
            tServBorda.start();
        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(0));
        } catch (IndexOutOfBoundsException ex) {

        }


    }//GEN-LAST:event_btIniciaMouseClicked

    private void btCadastraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastraMouseClicked
        // TODO add your handling code here:
        String nome, senha;
        Double saldo;

        nome = tfNome.getText();
        senha = tfSenha.getText();
        saldo = Double.parseDouble(tfSaldo.getText());
        Cliente c = new Cliente(nome, saldo, senha);
        SharedResources.getInstance().getClientes().add(c);

        tfNome.setText("");
        tfSenha.setText("");
        tfSaldo.setText("");

        JOptionPane.showMessageDialog(null, "Cliente cadastrado!");

        try {
            connectionServArq = new Socket(SharedResources.getInstance().getServers().get(0), 9000);
            TrataConexaoServidorArquivo trataServidoresArq;
            trataServidoresArq = new TrataConexaoServidorArquivo(connectionServArq, c, "enviaCliente");
            tServArq = new Thread(trataServidoresArq);
            tServArq.start();
            System.out.println("Enviei cliente!");
        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(0));
        } catch (IndexOutOfBoundsException ex) {

        }

        try {
            connectionServLog = new Socket(SharedResources.getInstance().getServers().get(1), 8090);
            TrataConexaoServidorLog trataServidoresLog;
            trataServidoresLog = new TrataConexaoServidorLog(connectionServLog, "Cliente cadastrado: " + c.getNome() + "\n");
            tServLog = new Thread(trataServidoresLog);
            tServLog.start();
        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(0));
        } catch (IndexOutOfBoundsException ex) {

        }

        int index = SharedResources.getInstance().getClientes().size() - 1;
        boolean sucesso = false;

        try {
            if (resultIp.equals(SharedResources.getInstance().getServers().get(0)) == false) {
                connectionServ = new Socket(SharedResources.getInstance().getServers().get(0), 8080);
                TrataConexaoServidores trataServidores;
                trataServidores = new TrataConexaoServidores(connectionServ, "cliente", index, saldo, c.getNome());
                tServ = new Thread(trataServidores);
                tServ.start();
            }

        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(0));
        } catch (IndexOutOfBoundsException ex) {

        }

        try {
            if (resultIp.equals(SharedResources.getInstance().getServers().get(1)) == false) {
                connectionServ = new Socket(SharedResources.getInstance().getServers().get(1), 8080);
                TrataConexaoServidores trataServidores;
                trataServidores = new TrataConexaoServidores(connectionServ, "cliente", index, saldo, c.getNome());
                tServ = new Thread(trataServidores);
                tServ.start();
            }

        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(1));
        } catch (IndexOutOfBoundsException ex) {

        }

        try {
            if (resultIp.equals(SharedResources.getInstance().getServers().get(2)) == false) {
                connectionServ = new Socket(SharedResources.getInstance().getServers().get(2), 8080);
                TrataConexaoServidores trataServidores;
                trataServidores = new TrataConexaoServidores(connectionServ, "cliente", index, saldo, c.getNome());
                tServ = new Thread(trataServidores);
                tServ.start();
            }

        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(2));

        } catch (IndexOutOfBoundsException ex) {

        }

        try {
            if (resultIp.equals(SharedResources.getInstance().getServers().get(3)) == false) {
                connectionServ = new Socket(SharedResources.getInstance().getServers().get(3), 8080);
                TrataConexaoServidores trataServidores;
                trataServidores = new TrataConexaoServidores(connectionServ, "cliente", index, saldo, c.getNome());
                tServ = new Thread(trataServidores);
                tServ.start();
            }

        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(3));
        } catch (IndexOutOfBoundsException ex) {

        }

    }//GEN-LAST:event_btCadastraMouseClicked

    private void btParaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btParaMouseClicked
        // TODO add your handling code here:
        mySocket.disconnect();
        lbStatus.setText("OFFLINE");
        lbStatus.setForeground(Color.red);

    }//GEN-LAST:event_btParaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
                
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastra;
    private javax.swing.JButton btInicia;
    private javax.swing.JButton btPara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbIp;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables

    private  void recebeClientes() {
        try {
            connectionServArq = new Socket(SharedResources.getInstance().getServers().get(0), 9000);
            TrataConexaoServidorArquivo trataServidoresArq;
            trataServidoresArq = new TrataConexaoServidorArquivo(connectionServArq, null, "recebeCliente");
            tServArq = new Thread(trataServidoresArq);
            tServArq.start();
            System.out.println("Enviei cliente!");
        } catch (IOException ex) {
            System.out.println("Falha ao conectar ao servidor: " + SharedResources.getInstance().getServers().get(0));
        } catch (IndexOutOfBoundsException ex) {

        }
    }
}
