/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor_borda_simuladorbancario;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.Socket;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author rafael
 */
public class GUI_BORDA extends javax.swing.JFrame {

    private MyServerSocket mySocket;
    private MyServerSocket mySocketCliente;
    private Thread t;
    private Thread tCliente;
    private Socket connectionServ;
    private DataInputStream dis = null;
    private DataOutputStream dos = null;
    private String resultIp = null;

    /**
     * Creates new form GUI2
     */
    public GUI_BORDA() {
        initComponents();
    }

    public static InetAddress getCurrentIp() {
        try {
            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface
                    .getNetworkInterfaces();
            while (networkInterfaces.hasMoreElements()) {
                NetworkInterface ni = (NetworkInterface) networkInterfaces
                        .nextElement();
                Enumeration<InetAddress> nias = ni.getInetAddresses();
                while (nias.hasMoreElements()) {
                    InetAddress ia = (InetAddress) nias.nextElement();
                    if (!ia.isLinkLocalAddress()
                            && !ia.isLoopbackAddress()
                            && ia instanceof Inet4Address) {
                        return ia;
                    }
                }
            }
        } catch (SocketException e) {
            //LOG.error("unable to get current IP " + e.getMessage(), e);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        btInicia = new javax.swing.JButton();
        btPara = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbIp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbIP1 = new javax.swing.JLabel();
        lbQTD1 = new javax.swing.JLabel();
        lbIP2 = new javax.swing.JLabel();
        lbQTD2 = new javax.swing.JLabel();
        lbIP3 = new javax.swing.JLabel();
        lbQTD3 = new javax.swing.JLabel();
        lbIP4 = new javax.swing.JLabel();
        lbQTD4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVIDOR DE BORDA");
        setFocusable(false);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Status do Servidor:");

        lbStatus.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 0, 0));
        lbStatus.setText("OFFLINE");

        btInicia.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btInicia.setText("Iniciar Servidor");
        btInicia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciaMouseClicked(evt);
            }
        });

        btPara.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btPara.setText("Parar Servidor");
        btPara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btParaMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("OPÇÕES:");

        lbIp.setText("0.0.0.0");

        jLabel2.setText("Servidor de Borda");

        jLabel3.setText("Servidores ONLINE:");

        jLabel4.setText("IP:");

        jLabel5.setText("Qtd_Clientes_Conectados");

        lbIP1.setText("0.0.0.0");

        lbQTD1.setText("0");

        lbIP2.setText("0.0.0.0");

        lbQTD2.setText("0");

        lbIP3.setText("0.0.0.0");

        lbQTD3.setText("0");

        lbIP4.setText("0.0.0.0");

        lbQTD4.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbIP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btInicia)
                                    .addGap(18, 18, 18)
                                    .addComponent(btPara))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGap(100, 100, 100))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbQTD3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbQTD2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbQTD1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbQTD4)
                                        .addComponent(jLabel5))))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(lbStatus)
                        .addGap(34, 34, 34)
                        .addComponent(lbIp)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(lbIP1)
                            .addComponent(lbIP2)
                            .addComponent(lbIP4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInicia)
                    .addComponent(btPara))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIP1)
                    .addComponent(lbQTD1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIP2)
                    .addComponent(lbQTD2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQTD3)
                    .addComponent(lbIP3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIP4)
                    .addComponent(lbQTD4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbStatus)
                    .addComponent(lbIp))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Servidor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btParaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btParaMouseClicked
        // TODO add your handling code here:
        mySocket.disconnect();
        mySocketCliente.disconnect();
        lbStatus.setText("OFFLINE");
        lbStatus.setForeground(Color.red);

    }//GEN-LAST:event_btParaMouseClicked

    private void btIniciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciaMouseClicked
        mySocket = new MyServerSocket();
        mySocketCliente = new MyServerSocketCliente();
        
        t = new Thread(mySocket);
        tCliente = new Thread(mySocketCliente);
        
        t.start();
        tCliente.start();
        
        
        lbStatus.setText("ONLINE");
        lbStatus.setForeground(Color.green);
        resultIp = GUI_BORDA.getCurrentIp().toString().replace("/", "");
        
        
    
        lbIp.setText(resultIp);

    }//GEN-LAST:event_btIniciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_BORDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_BORDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_BORDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_BORDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_BORDA().setVisible(true);
               
            }

            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInicia;
    private javax.swing.JButton btPara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JLabel lbIP1;
    private static javax.swing.JLabel lbIP2;
    private static javax.swing.JLabel lbIP3;
    private static javax.swing.JLabel lbIP4;
    private javax.swing.JLabel lbIp;
    private static javax.swing.JLabel lbQTD1;
    private static javax.swing.JLabel lbQTD2;
    private static javax.swing.JLabel lbQTD3;
    private static javax.swing.JLabel lbQTD4;
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables

    public static JLabel getLbIP1() {
        return lbIP1;
    }

    public static void setLbIP1(JLabel lbIP1) {
        GUI_BORDA.lbIP1 = lbIP1;
    }

    public static JLabel getLbIP2() {
        return lbIP2;
    }

    public static void setLbIP2(JLabel lbIP2) {
        GUI_BORDA.lbIP2 = lbIP2;
    }

    public static JLabel getLbIP3() {
        return lbIP3;
    }

    public static void setLbIP3(JLabel lbIP3) {
        GUI_BORDA.lbIP3 = lbIP3;
    }

    public static JLabel getLbIP4() {
        return lbIP4;
    }

    public static void setLbIP4(JLabel lbIP4) {
        GUI_BORDA.lbIP4 = lbIP4;
    }

    public static JLabel getLbQTD1() {
        return lbQTD1;
    }

    public static void setLbQTD1(JLabel lbQTD1) {
        GUI_BORDA.lbQTD1 = lbQTD1;
    }

    public static JLabel getLbQTD2() {
        return lbQTD2;
    }

    public static void setLbQTD2(JLabel lbQTD2) {
        GUI_BORDA.lbQTD2 = lbQTD2;
    }

    public static JLabel getLbQTD3() {
        return lbQTD3;
    }

    public static void setLbQTD3(JLabel lbQTD3) {
        GUI_BORDA.lbQTD3 = lbQTD3;
    }

    public static JLabel getLbQTD4() {
        return lbQTD4;
    }

    public static void setLbQTD4(JLabel lbQTD4) {
        GUI_BORDA.lbQTD4 = lbQTD4;
    }


}
